apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: basic-voting-vc
spec:
  hosts:
  - "*"
  gateways:
  - vote-gateway
  http:
  - match:
    - uri:
        exact: /vote
    - uri:
        prefix: /static/*
    route:
    - destination:
        host: vote-app
        port:
          number: 8080


